spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    env:
      enabled: true
    logfile:
      enabled: true
    loggers:
      enabled: true
    mappings:
      enabled: true
    configprops:
      enabled: true
    scheduledtasks:
      enabled: true
    metrics:
      enabled: true
    gateway:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"